### ISSUE TITLE
Make Semigroup a superclass of Monoid?

### ISSUE THREAD

**Issue by erikd-ambiata** [ambiata/p#116]
For ghc 8.0, `Semigroup` became a superclass of `Monoid` (see https://ghc.haskell.org/trac/ghc/ticket/10365 ).  This causes a problem in that the `<>` operator is now defined in both type classes and I have now had to do:
```
import           P hiding ((<>))
import           Data.Semigroup ((<>))
```
for a data type (Megaparsec's `Pos`) that had a `Semigroup` instance but not a `Monoid` one.

The future plans for GHC are here : https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid

Do we want to fix that in `P` now (or soon) rather than waiting for upstream?

**Comment by charleso** [comment]
Dupe? https://github.com/ambiata/p/issues/74

**Comment by erikd-ambiata** [comment]
Yes, dupe. Closing.
