### ISSUE TITLE
Adding Enum and Bounded

### ISSUE THREAD

**Issue by nhibberd** [ambiata/p#51]
Do people have any preferences if we add these to `P`
Possibly whitelist that is safe - `(Enum, Bounded, minBound, maxBound)`

**Comment by charleso** [comment]
Abstain. But it seems pretty safe at a glance.

**Comment by domdere** [comment]
Objection!

**Comment by domdere** [comment]
Sustained!

**Comment by jystic** [comment]
Yeah I'm all for it :beers: 

I already know code I wrote recently that will break though because I stupidly used `pred` as the name of a predicate.

**Comment by jystic** [comment]
My only objection would be that it's a terrible idea to store values extracted from the Enum instance anywhere because reordering the type will change the number. That should be caught in code review though.

**Comment by markhibberd** [comment]
> My only objection would be that it's a terrible idea to store values extracted from the Enum instance anywhere because reordering the type will change the number. That should be caught in code review though.

Not exporting to/from enum help there?

**Comment by jystic** [comment]
> > My only objection would be that it's a terrible idea to store values extracted from the Enum instance anywhere because reordering the type will change the number. That should be caught in code review though.
>
> Not exporting to/from enum help there? 

Yeah that's a good idea, there's probably not a good reason to be using those. Hopefully that doesn't prevent deriving.

**Comment by nhibberd** [comment]
`P.Prelude` ?
