### ISSUE TITLE
Strict functions missing from P.

### ISSUE THREAD

**Issue by markhibberd** [ambiata/p#53]
Just noticed on a different `PR` we are a bit light on some of the strict/forcing functions `$!` being an important one which I have seen re-implemented (non-optimally) a few times with bang patterns, that it would be good to expose.

**Comment by jystic** [comment]
I think we have all the strict functions from `base` exposed by P now

**Comment by jystic** [comment]
We probably should have `$!!`, `deepseq` and maybe `force` from [Control.DeepSeq](http://hackage.haskell.org/package/deepseq-1.4.1.2/docs/Control-DeepSeq.html) too

**Comment by thumphries** [comment]
> We probably should have $!!, deepseq and maybe force from Control.DeepSeq too

already there https://github.com/ambiata/p/blob/master/src/P.hs#L41

**Comment by jystic** [comment]
Haha ok then, this issue is well and truly done in that case
