### ISSUE TITLE
RFC: strict Maybe

### ISSUE THREAD

**Issue by olorin** [ambiata/p#93]
What do y'all think of exporting the strict version of `Maybe` from [here](https://hackage.haskell.org/package/strict-0.3.2/docs/Data-Strict-Maybe.html) rather than the `Prelude` version? Could potentially save a lot of pain memory-wise.

Alternatively, we could just expose a `Maybe'`alias for the strict `Maybe` and have it alongside the lazy one?

@ambiata/engineers

**Comment by markhibberd** [comment]
👍 For `Maybe'` I don't think same name works when the semantics change (compared with EitherT as an alternative example which has identical semantics).

**Comment by markhibberd** [comment]
Looking at this again, given the sparsity (und lack of safety) of the library exposed from that version maybe having our own with `Just'` and `Nothing'` constructors makes sense?

**Comment by olorin** [comment]
> Looking at this again, given the sparsity (and lack of safety) of the library exposed from that version maybe having our own with Just' and Nothing' constructors makes sense?

That works for me. Will implement that if no-one objects.
